In [1]:
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.utils import np_utils

batch_size = 128
nb_classes = 10
nb_epoch = 12

# input image dimensions
img_rows, img_cols = 28, 28
# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

# the data, shuffled and split between tran and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()

model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='valid',
                        input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adadelta')

model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          show_accuracy=True, verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, show_accuracy=True, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Using Theano backend.
/Users/gordon/src/music-gen/.direnv/python-3.5.0/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")


X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 1345s - loss: 0.2340 - acc: 0.9281 - val_loss: 0.0557 - val_acc: 0.9833
Epoch 2/12
60000/60000 [==============================] - 1188s - loss: 0.0870 - acc: 0.9738 - val_loss: 0.0430 - val_acc: 0.9853
Epoch 3/12
60000/60000 [==============================] - 1322s - loss: 0.0667 - acc: 0.9800 - val_loss: 0.0314 - val_acc: 0.9903
Epoch 4/12
60000/60000 [==============================] - 1213s - loss: 0.0529 - acc: 0.9841 - val_loss: 0.0295 - val_acc: 0.9905
Epoch 5/12
60000/60000 [==============================] - 1159s - loss: 0.0476 - acc: 0.9851 - val_loss: 0.0286 - val_acc: 0.9901
Epoch 6/12
60000/60000 [==============================] - 1159s - loss: 0.0418 - acc: 0.9865 - val_loss: 0.0328 - val_acc: 0.9889
Epoch 7/12
60000/60000 [==============================] - 1160s - loss: 0.0395 - acc: 0.9877 - va

In [3]:
model.predict??

In [31]:
X_test[0]

array([[[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.  

In [10]:
json_string = model.to_json()

In [11]:
open('conv_mnist_architecture.json', 'w').write(json_string)

2495

In [14]:
model.save_weights('conv_mnist_weights.h5')

In [1]:
from keras.models import model_from_json
model = model_from_json(open('conv_mnist_architecture.json').read())
model.load_weights('conv_mnist_weights.h5')


Using Theano backend.
/Users/gordon/src/music-gen/.direnv/python-3.5.0/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")


In [5]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [7]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [3]:
batch_size = 128
nb_classes = 10
nb_epoch = 12

# input image dimensions
img_rows, img_cols = 28, 28
# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [11]:
from PIL import Image

Image.fromarray(X_test[33])

In [12]:
input()

Cool.


'Cool.'

In [15]:
input("whoa ")
input("other thing")

whoa thing
other thing


''

In [10]:
"Hello {name}".format(name="Alex")

'Hello Alex'

In [12]:
model.predict??

In [36]:
specific_test = [X_test[0]]

In [37]:
model.predict(X_test)

array([[  2.03324675e-13,   1.16875010e-12,   8.54413979e-13, ...,
          1.00000000e+00,   4.56064308e-15,   1.71711204e-11],
       [  2.27711539e-09,   9.43392209e-08,   9.99999881e-01, ...,
          1.93751751e-11,   9.20672306e-12,   4.26749632e-14],
       [  1.11089767e-13,   1.00000000e+00,   4.40923556e-12, ...,
          7.88312263e-11,   5.39393747e-12,   1.00981886e-12],
       ..., 
       [  2.14806255e-19,   5.48344573e-13,   3.70812273e-19, ...,
          1.95554624e-15,   6.14829672e-12,   4.11656126e-11],
       [  1.40372878e-11,   1.70980214e-13,   1.45088326e-16, ...,
          5.95492752e-12,   8.39548946e-08,   2.41795126e-12],
       [  2.70415201e-09,   2.54818423e-11,   1.33676861e-10, ...,
          2.39574884e-14,   1.29402964e-11,   1.74036919e-13]])

In [38]:
predictions = _

In [39]:
predictions[0]

array([  2.03324675e-13,   1.16875010e-12,   8.54413979e-13,
         1.09223334e-11,   3.94526686e-15,   1.49410503e-15,
         2.13159233e-17,   1.00000000e+00,   4.56064308e-15,
         1.71711204e-11])

In [26]:
from keras.utils import np_utils

In [40]:
np_utils.categorical_probas_to_classes(predictions)

array([7, 2, 1, ..., 4, 5, 6])

In [32]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()